# Generated by Django 3.1.4 on 2020-12-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceNo', models.AutoField(primary_key=True, serialize=False)),
                ('serviceType', models.CharField(max_length=100)),
                ('serviceName', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
    ]
